version: '3.8'

services:
  web:
    build: ./webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../:/var/www/"
    depends_on:
      - db
    links:
      - db
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      CUSTOM_SERVER_NAME: "example.loc"

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
    driver: local
  webdav_data:
    driver: local

